# Generated by Django 3.1.3 on 2020-12-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
