# Generated by Django 3.2 on 2021-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="password",
            field=models.CharField(
                default="pass",
                help_text="Password used to join the team",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
