# Generated by Django 3.2 on 2021-04-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(help_text='Password used to join the team', max_length=128),
        ),
    ]
