# Generated by Django 3.2 on 2021-05-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='refresh_interval',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
