# Generated by Django 3.2 on 2021-05-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
