# Generated by Django 3.2.3 on 2021-06-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskinstance_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinstancecompletion',
            name='points_granted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
